title: "Chuck’s casse-croûte"
description: "Poutines généreuses, burgers débordants et casse-croûte familial à Gatineau."

# Logo utilisé par le thème Minimal
logo: /assets/images/logo.png
show_downloads: false

# Domaine principal du site
url: "https://chucks-casse-croute.com"
baseurl: ""   # IMPORTANT : vide car tu utilises un nom de domaine custom

# SEO / Langues
lang: fr-CA

languages:
  - fr
  - en

defaults:
  - scope:
      path: ""
    values:
      lang: fr
  - scope:
      path: "en"
    values:
      lang: en

# Plugins GitHub Pages (sitemap auto)
plugins:
  - jekyll-sitemap
